openapi: "3.0.3"
info:
  title: "Kotlin IDE Integration API"
  description: "API for Kotlin code validation and execution"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
    description: "Local development server"
paths:
  /:
    get:
      summary: "Redirect to index page"
      description: "Redirects to the main index.html page"
      responses:
        "302":
          description: "Redirect to /index.html"
          headers:
            Location:
              schema:
                type: "string"
                example: "/index.html"
  /validate-code:
    post:
      summary: "Validate Kotlin code"
      description: "Parses and validates Kotlin code syntax"
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: "string"
              description: "Kotlin code to validate"
              example: |
                fun main() {
                    println("Hello, World!")
                }
      responses:
        "200":
          description: "Validation result"
          content:
            application/json:
              schema:
                type: "object"
                description: "Parse result with syntax information"
              examples:
                Example#1:
                  value: |
                    {
                      "success": true,
                      "errors": []
                    }
  /run-code:
    post:
      summary: "Execute Kotlin code"
      description: "Compiles and runs the provided Kotlin code"
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: "string"
              description: "Kotlin code to execute"
              example: |
                fun main() {
                    println("Hello, World!")
                }
      responses:
        "200":
          description: "Execution result"
          content:
            text/plain:
              schema:
                type: "string"
                description: "Output from the executed code"
components:
  schemas: {}
